export default {
    CLEAR_INPUT: 'CLEAR_INPUT',
    CLEAR_TRACE: 'CLEAR_TRACE',
    PROMPT_INPUT: 'PROMPT_INPUT',
    RESET: 'RESET',
    SEND_INPUT: 'SEND_INPUT',
    SET_STEP: 'SET_STEP',
    UPDATE_CONSOLE: 'UPDATE_CONSOLE',
    UPDATE_STEPPING: 'UPDATE_STEPPING',
    UPDATE_TRACE: 'UPDATE_TRACE',
}