const CLEAR_INPUT = 'CLEAR_INPUT'
const CLEAR_TRACE = 'CLEAR_TRACE'
const PROMPT_INPUT = 'PROMPT_INPUT'
const RESET = 'RESET'
const SEND_INPUT = 'SEND_INPUT'
const UPDATE_CONSOLE = 'UPDATE_CONSOLE'
const UPDATE_TRACE = 'UPDATE_TRACE'

export default {
    CLEAR_INPUT,
    CLEAR_TRACE,
    PROMPT_INPUT,
    RESET,
    SEND_INPUT,
    UPDATE_CONSOLE,
    UPDATE_TRACE,
}