const CLEAR_INPUT = 'CLEAR_INPUT'
const PROMPT_INPUT = 'PROMPT_INPUT'
const RESET = 'RESET'
const SEND_INPUT = 'SEND_INPUT'
const UPDATE_CONSOLE = 'UPDATE_CONSOLE'

export default {
    CLEAR_INPUT,
    PROMPT_INPUT,
    RESET,
    SEND_INPUT,
    UPDATE_CONSOLE,
}